// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class Applocalizations extends AssetLoader {
  const Applocalizations();

  static const enCode = 'en';
  static const plCode = 'pl';
  static const localeEn = Locale(enCode);
  static const localePl = Locale(plCode);
  static const List<Locale> supportedLocales = <Locale>[localeEn, localePl];

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> en = {
    "title": "Poland",
    "appTitle": 'ReClimb PL',
    "climb": 'Climb',
    "home": 'Home',
    "profile": 'Profile',
    "reservations": 'Reservations',
    "routes": 'Routes',
    "appName": 'Climb',
    "nextClimb": 'Next Climb',
    "designed": 'Designed',
    "favourite": 'Favorite',
    "history": 'History',
    "playlist": 'Playlist',
    "route": 'route',
    "filter": 'Filter',
    "sort": 'Sort',
    "addToPlaylist": 'Add playlist',
    "copy": 'Copy',
    "delete": 'Delete',
    "edit": 'Edit',
    "moveToPlaylist": 'Move to playlist top',
    "removeFromFavorite": 'Remove from favourite',
    "removeFromPlaylist": 'Remove from playlist',
    "share": 'Share',
    "addToFavourite": 'Add to favourite',
    "select": 'Select',
    "author": 'Author',
    "authorGrade": "Author's Grade",
    "authorsGrade": "Author's Grade",
    "corners": "Corners",
    "designedBy": 'Designed by',
    "friends": 'Friends',
    "notTried": 'Not Tried',
    "osOnSight": 'OS-OnSight',
    "removeFilter": 'Remove Filter',
    "routeSetter": 'Route Setter',
    "rpRedPoint": 'RP-Red Point',
    "showResult": 'Show Result',
    "status": 'Status',
    "suSupported": 'SU-Supported',
    "trTopRope": 'TR-Top-rope',
    "ufUnfinished": 'UF-Unfinished',
    "userGrade": "User's Grade",
    "withCorner": "With corners",
    "withoutCorners": "Without Corners",
    "notItemSelect": 'Not item select, please try again.',
    "hinTextSearchHome": 'Find places, route, climbs',
    "all": 'All',
    "persons": 'Persons',
    "places": 'Places',
    "user": 'User',
    "popularity": 'Popularity',
    "info": 'info',
    "nextWeek": 'Next week',
    "today": 'Today',
    "tomorrow": 'Tomorrow',
    "countDesigned": 'DESIGNED',
    "countFriends": 'FRIENDS',
    "countPassed": 'PASSED',
    "editSettings": 'Edit Settings',
    "tabDesigned": 'Designed',
    "tabHistory": 'History',
    "tabPosts": 'Posts',
    "settingsAccount": 'Account',
    "settings": 'Settings',
    "settingsNotifications": 'Notifications',
    "settingsPrivacy": 'Privacy',
    "settingsGeneral": 'General',
    "account_change_photo": 'Change photo',
    "account_email": 'E-MAIL ADDRESS',
    "account_favorite_route_grade": 'FAVORITE ROUTE GRADE',
    "account_height": 'HEIGHT',
    "account_name": 'NAME',
    "account_nickname": 'NICKNAME',
    "account_surname": 'SURNAME',
    "account_type": 'TYPE',
    "cancelYourReservation": 'Cancel your reservation',
    "newReservation": 'New reservation',
    "city": 'City',
    "place": 'Place',
    "hours": 'Hours',
    "friday": 'Friday',
    "seeAll": 'See all',
    "friend": 'FRIENDS',
    "topRouteSetter": "TOP ROUTE SETTER",
    "holdSet": "Holds set",
    "list": "List",
    "map": "Map",
    "wallHeight": "Wall Height",
    "notif_comments": 'Comments',
    "notif_invitation_to_friends": 'Invitation to friends',
    "notif_likes": 'Likes',
    "notif_push_notifications": 'Push Notification',
    "notif_reservations": 'Reservations',
    "notif_sharing": 'Sharing',
    "reclimb_available_in": 'Reclimb is available in',
    "privacy_friends": 'Friends',
    "privacy_friends_list": 'MY FRIENDS LIST',
    "privacy_post": 'DEFAULT POST VISIBILITY',
    "privacy_private": 'Private',
    "privacy_public": 'Public',
    "privacy_routes": 'DEFAULT ROUTES VISIBILITY',
    "privacy_video": 'DEFAULT VIDEO VISIBILITY',
    "general_settings_grade_scale": 'GRADE SCALE',
    "general_settings_grade_scale_british": 'British',
    "general_settings_grade_scale_french": 'French',
    "general_settings_grade_scale_nordic": 'Nordic',
    "general_settings_grade_scale_usa": 'USA',
    "general_settings_language": 'LANGUAGE',
    "general_settings_language_english": 'English',
    "general_settings_language_poland": 'Poland',
    "general_settings_system_measurement": 'SYSTEM OF MEASUREMENT',
    "general_settings_system_measurement_imperial_units": 'Imperial Units',
    "general_settings_system_measurement_meters": 'Metric - meters',
    "find_place": 'Find place',
    "find_city": 'Find City',
    "please_input_information": 'Please input infomation',
    "confirm_information": 'Confirm information',
    "wall": 'Wall',
    "check_your_email": 'Check your e-mail',
    "it_is_not_reservation":
        "Please check your e-mail to confirm your\nreservation. If you can't find our message\ncheck spam or offers folder.",
    "please_check_mail": "It isn't reservation confirmation",
    "cancel": 'Cancel',
    "save_daft": 'Save daft',
    "select_hold": 'Select hold',
    "double_tab_to_see_3d_preview": 'Double tab to see 3D preview',
    "type": 'Type',
    "td": '3D',
    "next_climp": 'Next climp',
    "likes": 'likes',
    "comment": 'comment',
    "show_more": "Show more",
    "bluetooth": "Bluetooth",
    "pleaseTurnOnBl":
        "Please turn on Bluetooth to connect to the \n nearest ReClimb wall",
    "turnOnBluetooth": "Turn on Bluetooth",
    "cantFind":
        "I can't find any ReClimb wall near you.\n Please turn on location to get more precise\n result ",
    "connectToTheReClimb":
        'To connect to the ReClimb wall, move closer \n than 10 meters.',
    "getCloser": 'Get closer',
    "turnOnLocation": 'Turn on location',
    "theNearest": "THE NEAREST PLACES",
    "create_routes": 'Create routes',
    "find_routes": 'Find routes',
    "add_favourite": 'Add favorite',
    "notifications": 'Notifications',
    "invitations": 'Invitations',
    "activities": 'Activities',
    "add_to_friends": 'Add to friends',
    "reject": 'Reject',
    "login": 'Login',
    "youNeedLogin": 'You need to login to use\n this service',
    "logOut": 'LogOut',
    "please_input_email": 'Please enter your Email',
    "please_input_pass": 'Please enter your Password',
    "please_input_valid_email": 'Please enter valid Email',
    "please_input_valid_pass": 'Please enter valid Password',
    "network_error": 'Network error, please try again.',
    "login_success": 'Login success.',
    "logout_success": 'LogOut Success',
    "thisFeatureIsUnder": "This feature is under\nconstruction",
    "last_visited_place": 'Last visited place',
    "the_nearest_place": 'The nearest place',
    "action": "Action",
    "not_data": 'Not data, please try again.',
    "address": 'Address',
    "photos": "Photos",
    "schedule": "Schedule",
    "corner": 'corner',
    "publish": 'Publish',
    "route_name": 'Route name',
    "who_can_see_this_route": 'Who can see this route',
    "grade": 'Grade',
    "please_input_hold_set": 'Please input hold set',
    "briefly_touch_surface_with_fingertip":
        'Briefly touch surface\nwith fingertip',
    "edit_route": 'Edit route',
    "next": 'Next',
    "pinch_to_scale_down_and_up": 'Pinch to scale down and up',
    "press_cell_with_hold_to_move_it_or_rotate_it":
        'Press cell with hold to move it or rotate it',
    "tab_on_cell_to_select_hold": 'Tap on cell to select hold',
    "touch_suface_for_extended_privod_of_time":
        'Touch surface for\nextended period of\ntime',
    "touch_surface_with_two_fingers_and_bring_them_closer_together":
        'Touch surface with two\nfingers and bring them\ncloser together',
    "defaultArrangement": "Default arrangement",
    "sortBy": "SORT BY",
    "theRouteName": "The route’s name: A-Z",
    "authorDes": "The author’s grade: descending",
    "authorAsc": "The author’s grade: ascending",
    "userDes": "The user’s grade: descending",
    "userAsc" : "The user’s grade: ascending"
  };

  static const Map<String, dynamic> pl = {
    "title": "English",
    "appTitle": 'ReClimb',
    "climb": 'Climb',
    "home": 'Home',
    "profile": 'Profile',
    "reservations": 'Reservations',
    "routes": 'Routes',
    "appName": 'Climb',
    "nextClimb": 'Next Climb',
    "designed": 'Designed',
    "favourite": 'Favorite',
    "history": 'History',
    "playlist": 'Playlist',
    "route": 'route',
    "filter": 'Filter',
    "sort": 'Sort',
    "addToPlaylist": 'Add playlist',
    "copy": 'Copy',
    "delete": 'Delete',
    "edit": 'Edit',
    "moveToPlaylist": 'Move to playlist top',
    "removeFromFavorite": 'Remove from favourite',
    "removeFromPlaylist": 'Remove from playlist',
    "share": 'Share',
    "addToFavourite": 'Add to favourite',
    "select": 'Select',
    "author": 'Author',
    "authorGrade": "Author's Grade",
    "authorsGrade": "Author's Grade",
    "corners": "Corners",
    "designedBy": 'Designed by',
    "friends": 'Friends',
    "notTried": 'Not Tried',
    "osOnSight": 'OS-OnSight',
    "removeFilter": 'Remove Filter',
    "routeSetter": 'Route Setter',
    "rpRedPoint": 'RP-Red Point',
    "showResult": 'Show Result',
    "status": 'Status',
    "suSupported": 'SU-Supported',
    "trTopRope": 'TR-Top-rope',
    "ufUnfinished": 'UF-Unfinished',
    "userGrade": "User's Grade",
    "withCorner": "With corners",
    "withoutCorners": "Without Corners",
    "notItemSelect": 'Not item select, please try again.',
    "hinTextSearchHome": 'Find places, route, climbs',
    "all": 'All',
    "persons": 'Persons',
    "places": 'Places',
    "user": 'User',
    "popularity": 'Popularity',
    "info": 'info',
    "nextWeek": 'Next week',
    "today": 'Today',
    "tomorrow": 'Tomorrow',
    "countDesigned": 'DESIGNED',
    "countFriends": 'FRIENDS',
    "countPassed": 'PASSED',
    "editSettings": 'Edit Settings',
    "tabDesigned": 'Designed',
    "tabHistory": 'History',
    "tabPosts": 'Posts',
    "settingsAccount": 'Account PL',
    "settings": 'Settings PL',
    "settingsNotifications": 'Notifications PL',
    "settingsPrivacy": 'Privacy PL',
    "settingsGeneral": 'General Pl',
    "account_change_photo": 'Change photo',
    "account_email": 'E-MAIL ADDRESS',
    "account_favorite_route_grade": 'FAVORITE ROUTE GRADE',
    "account_height": 'HEIGHT',
    "account_name": 'NAME',
    "account_nickname": 'NICKNAME',
    "account_surname": 'SURNAME',
    "account_type": 'TYPE',
    "cancelYourReservation": 'Cancel your reservation',
    "newReservation": 'New reservation',
    "city": 'City',
    "place": 'Place',
    "hours": 'Hours',
    "friday": 'Friday',
    "seeAll": 'See all',
    "friend": 'FRIENDS',
    "topRouteSetter": "TOP ROUTE SETTER",
    "holdSet": "Holds set",
    "list": "List",
    "map": "Map",
    "wallHeight": "Wall Height",
    "notif_comments": 'Comments',
    "notif_invitation_to_friends": 'Invitation to friends',
    "notif_likes": 'Likes',
    "notif_push_notifications": 'Push Notification',
    "notif_reservations": 'Reservations',
    "notif_sharing": 'Sharing',
    "reclimb_available_in": 'Reclimb is available in',
    "privacy_friends": 'Friends',
    "privacy_friends_list": 'MY FRIENDS LIST',
    "privacy_post": 'DEFAULT POST VISIBILITY',
    "privacy_private": 'Private',
    "privacy_public": 'Public',
    "privacy_routes": 'DEFAULT ROUTES VISIBILITY',
    "privacy_video": 'DEFAULT VIDEO VISIBILITY',
    "general_settings_grade_scale": 'GRADE SCALE',
    "general_settings_grade_scale_british": 'British',
    "general_settings_grade_scale_french": 'French',
    "general_settings_grade_scale_nordic": 'Nordic',
    "general_settings_grade_scale_usa": 'USA',
    "general_settings_language": 'LANGUAGE',
    "general_settings_language_english": 'English',
    "general_settings_language_poland": 'Poland',
    "general_settings_system_measurement": 'SYSTEM OF MEASUREMENT',
    "general_settings_system_measurement_imperial_units": 'Imperial Units',
    "general_settings_system_measurement_meters": 'Metric - meters',
    "find_place": 'Find place',
    "find_city": 'Find City',
    "please_input_information": 'Please input infomation',
    "confirm_information": 'Confirm information',
    "wall": 'Wall',
    "check_your_email": 'Check your e-mail',
    "it_is_not_reservation":
        "Please check your e-mail to confirm your\nreservation. If you can't find our message\ncheck spam or offers folder.",
    "please_check_mail": "It isn't reservation confirmation",
    "cancel": 'Cancel',
    "save_daft": 'Save daft',
    "select_hold": 'Select hold',
    "double_tab_to_see_3d_preview": 'Double tab to see 3D preview',
    "type": 'Type',
    "td": '3D',
    "next_climp": 'Next climp',
    "likes": 'likes',
    "comment": 'comment',
    "show_more": "Show more",
    "bluetooth": "Bluetooth",
    "pleaseTurnOnBl":
        "Please turn on Bluetooth to connect to the \n nearest ReClimb wall",
    "turnOnBluetooth": "Turn on Bluetooth",
    "cantFind":
        "I can't find any ReClimb wall near you.\n Please turn on location to get more precise\n result ",
    "connectToTheReClimb":
        'To connect to the ReClimb wall, move closer \n than 10 meters.',
    "getCloser": 'Get closer',
    "turnOnLocation": 'Turn on location',
    "theNearest": "THE NEAREST PLACES",
    "create_routes": 'Create routes',
    "find_routes": 'Find routes',
    "add_favourite": 'Add favorite',
    "notifications": 'Notifications',
    "invitations": 'Invitations',
    "activities": 'Activities',
    "add_to_friends": 'Add to friends',
    "reject": 'Reject',
    "login": 'Login',
    "youNeedLogin": 'You need to login to use\n this service',
    "logOut": 'LogOut',
    "please_input_email": 'Please enter your Email',
    "please_input_pass": 'Please enter your Password',
    "please_input_valid_email": 'Please enter valid Email',
    "please_input_valid_pass": 'Please enter valid Password',
    "network_error": 'Network error, please try again.',
    "login_success": 'Login success.',
    "logout_success": 'LogOut Success',
    "thisFeatureIsUnder": "This feature is under\nconstruction",
    "last_visited_place": 'Last visited place',
    "the_nearest_place": 'The nearest place',
    "action": "Action",
    "not_data": 'Not data, please try again.',
    "address": 'Address',
    "photos": "Photos",
    "schedule": "Schedule",
    "corner": 'corner',
    "publish": 'Publish',
    "route_name": 'Route name',
    "who_can_see_this_route": 'Who can see this route',
    "grade": 'Grade',
    "please_input_hold_set": 'Please input hold set',
    "briefly_touch_surface_with_fingertip":
        'Briefly touch surface\nwith fingertip',
    "edit_route": 'Edit route',
    "next": 'Next',
    "pinch_to_scale_down_and_up": 'Pinch to scale down and up',
    "press_cell_with_hold_to_move_it_or_rotate_it":
        'Press cell with hold to move it or rotate it',
    "tab_on_cell_to_select_hold": 'Tap on cell to select hold',
    "touch_suface_for_extended_privod_of_time":
        'Touch surface for\nextended period of\ntime',
    "touch_surface_with_two_fingers_and_bring_them_closer_together":
        'Touch surface with two\nfingers and bring them\ncloser together',
    "defaultArrangement": "Default arrangement",
    "sortBy": "SORT BY",
    "theRouteName": "The route’s name: A-Z",
    "authorDes": "The author’s grade: descending",
    "authorAsc": "The author’s grade: ascending",
    "userDes": "The user’s grade: descending",
    "userAsc" : "The user’s grade: ascending"
  };

  static const Map<String, Map<String, dynamic>> mapLocales = {
    enCode: en,
    plCode: pl
  };
}
